### ISSUE TITLE
feature request: onend callback

### ISSUE THREAD

**Issue by micuat** [Jisuanke/CodeMirror-Record#21]
I wonder if you are planning to add handlers for playback events - especially `onend` would be super useful to trigger events when the playback is finished. I currently do so with an extra activity, which works fine as long as it's recorded in advance.

I can also PR but wanted to know how you think before going ahead.

**Comment by haoranyu** [comment]
The extra activity is designed to be able to use the same temporal reference frame to record other behaviors outside of the editor. It is not its original intention to use it as event control.

Your idea of adding events is great. I thought about adding events to the Player before, but I haven't done any related work yet. I will not do this part of the work in the near future. Your PR is very welcome.

**Comment by haoranyu** [comment]
This feature is supported. You may use `on` to bind `end` event now. @micuat.
