### ISSUE TITLE
recording and playing back special key combinations

### ISSUE THREAD

**Issue by polymorphicengine** [Jisuanke/CodeMirror-Record#30]
Hello!
I have bound some custom functions to special key-combinations. Is it possible that those will be recorded and when the key-combination occurs while playing back the function is triggered aswell? Can't really figure it out.
Thanks for your help.

**Comment by haoranyu** [comment]
At this stage, we have recorded mainstream codemirror events. Regarding the key-combination situation you mentioned, is it visible in the codemirror history?

If so, I think we should be able to record it.

**Comment by polymorphicengine** [comment]
Hey!
Unfortunately I don't think the pressed key-combinations are present in the undo history.
Do you think there is a way to add them?

**Comment by haoranyu** [comment]
> Hey!
> Unfortunately I don't think the pressed key-combinations are present in the undo history.
> Do you think there is a way to add them?

For this case, I suggest you directly use `extraActivityHandler` method we provide and capture the event in the outer environment.

You may refer to this document here: https://github.com/Jisuanke/CodeMirror-Record#initialize-a-player

**Comment by polymorphicengine** [comment]
Could you make an example of what `moreActivities` in `codeRecorder.recordExtraActivity(moreActivities);` could be?
I'm not very familiar with JS, so any help would be appreciated!

**Comment by haoranyu** [comment]
> Could you make an example of what `moreActivities` in `codeRecorder.recordExtraActivity(moreActivities);` could be?
> I'm not very familiar with JS, so any help would be appreciated!

For example, a key down event is triggered, then you may have a function like follows:

```js
domName.addEventListener('keydown', (e) => {
  // you may use the key described in the event parameter
  codeRecorder.recordExtraActivity({
    keyName: e.keyName,
    ctrlKey: e.ctrlKey,
    altKey: e.altKey,
    shiftKey: e.shiftKey,
  }) // let us record the key combination here
})
```

If then you wish to playback such an event, you may write another callback function to deal with the recorded "extra activity" when you set the `extraActivityHandler`.
