### ISSUE TITLE
Pausing Code Playback

### ISSUE THREAD

**Issue by jacobjzhang** [Jisuanke/CodeMirror-Record#7]
Hi team,

This is a really cool project. I tried the demo out and it works perfectly-- well done!

I would love to use this for my personal projects, and looked into the code for the ability to pause code playback. I noticed there was no way to stop playback and resume at a later time. How difficult would it to implement a feature like this?

**Comment by haoranyu** [comment]
> This is a really cool project. I tried the demo out and it works perfectly-- well done!
> 
> I would love to use this for my personal projects, and looked into the code for the ability to pause code playback. I noticed there was no way to stop playback and resume at a later time. How difficult would it to implement a feature like this?

Thank you for the feature request. 

Actually, we have similar requirement in our projects too. Pausing, resuming and also playing acceleration are already on our issue list. It would not be too hard to implement. I may take some time in August to finish it. You could expect to have such features in this project before October.

**Comment by haoranyu** [comment]
@jacobjzhang 

I spent some time this weekend and made some adjustments to the playback mechanism and API of the player. It seems that these adjustments are simpler than I expected.

So I added some new features and released [0.5.0](https://github.com/haoranyu/codemirror-record/releases/tag/v0.5.0). I don't know whether these features can perfectly solve this issue. Please let me know if the `pause` feature supported in this release is different from what you expected.

**Comment by jacobjzhang** [comment]
Hi @haoranyu,

Thanks so much! This is great. I just noticed one more issue-- that the README was calling the wrong method for pause: https://github.com/haoranyu/codemirror-record/compare/master...jacobjzhang:patch-1

Separate question-- is there a public roadmap? I would love to contribute.

**Comment by haoranyu** [comment]
> Hi @haoranyu,
> 
> Thanks so much! This is great. I just noticed one more issue-- that the README was calling the wrong method for pause: [master...jacobjzhang:patch-1](https://github.com/haoranyu/codemirror-record/compare/master...jacobjzhang:patch-1)
> 
> Separate question-- is there a public roadmap? I would love to contribute.

It is so nice to have the typo fixed in the PR!

Currently, there is no more active issue in our private repository.

And we are going to move this project from the original private repository to the public one here. More feature requests and PRs are welcome.
